#!/usr/bin/env bash
# Usage: i3dm session
# Summary: Starts i3dm session
# Help: it starts all pieces for i3dm session:
# - configures xrandr
# - initialize compositor
# - set wallpapers
# - enable screensaver
# - start all programs from ~/.config/autostart

source ${libs_file}

/usr/bin/lxsession -n & 

/bin/bash ${ROOT_DIR}/i3dm input
/bin/bash ${ROOT_DIR}/i3dm screenctl --no-wait
/bin/bash ${ROOT_DIR}/i3dm screensaver -e

notify i3dm Session started
sleep 30
