#!/usr/bin/env bash
# Usage: i3dm session
# Summary: Starts i3dm session
# Help: it starts all pieces for i3dm session:
# - configures xrandr
# - initialize compositor
# - set wallpapers
# - enable screensaver
# - start all programs from ~/.config/autostart

source ${libs_file}

/usr/bin/albert &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
dex -a ~/.config/autostart/

/bin/bash ${ROOT_DIR}/i3dm input
/bin/bash ${ROOT_DIR}/i3dm screenctl --no-wait
/bin/bash ${ROOT_DIR}/i3dm compositor
/bin/bash ${ROOT_DIR}/i3dm wallpaper
/bin/bash ${ROOT_DIR}/i3dm androidconnect
/bin/bash ${ROOT_DIR}/i3dm screensaver -e

notify i3dm Session started
sleep 30
