#!/usr/bin/env bash
# Usage: i3dm screenctl
# Summary: change screen configuration
# Help: Configure xrandr detected screens

set -x
source ${libs_file}

cmd=${1:-auto}

function auto_monitor() {
  if [ ${mons_num} -eq 2 ]; then
    mons -e ${MON_SIDE}
  elif [ ${mons_num} -eq 3 ]; then
    xrandr --output eDP-1 --mode 1920x1080 --output DP-1 --auto --right-of eDP-1 --output DP-2 --auto --rotate left --right-of DP-1
    xrandr --output DP-1 --scale 0.8x0.8 --output DP-2 --scale 0.8x0.8 --dpi 221
  else
    notify Screen "External monitor not detected"
    mons -o
  fi
}

function compositor() {
  compton --config ${i3dm_compton_config} -b
  feh --bg-fill --randomize ${i3dm_wallpapers_dir}/*
}


mons_num=$(mons | grep Monitors | awk '{print $2}')
notify Screen "${mons_num} monitor(s) detected"

case $cmd in
  ui|--ui)
    lxrandr
    exit
    ;;
  mirror)
    if [ $mons_num -eq 2 ]; then
      mons -m
    else
      log_i screen "Not possible to mirror screen"
      notify Screen "Not possible to mirror screen"
    fi
    ;;
  udev)
    log_i screen "udev monitor event received..."
    mons > /dev/null
    sleep 10s
    auto_monitor
    compositor
    ;;
  auto|*)
    auto_monitor
    compositor
  ;;
esac
