#!/usr/bin/env bash
# Usage: i3dm screenctl
# Summary: change screen configuration
# Help: Configure xrandr detected screens

set -xe
source ${libs_file}

cmd=${1:-auto}

function auto_monitor() {
  if [ ${mons_num} -eq 1 ]; then
    xrandr \
        --output eDP-1 \
        --auto \
        --dpi 96
  elif [ ${mons_num} -eq 2 ]; then
    mons -e ${MON_SIDE}
  elif [ ${mons_num} -eq 3 ]; then
    xrandr \
        --output edp-1 --mode 1920x1080 \
        --scale 1x1 \
        --output DP-1 --mode 3840x2160 --right-of eDP-1 \
        --scale 0.8x0.8 \
        --output DP-2 --mode 3840x2160 --right-of DP-1 --rotate left \
        --scale 0.8x0.8 \
        --dpi 221
  fi
}

function reset_xrandr() {
    xrandr -s 0
}

function compositor() {
  feh --bg-fill --randomize ${i3dm_wallpapers_dir}/*
  compton --config ${i3dm_compton_config} -b
}


mons_num=$(mons | grep Monitors | awk '{print $2}')

case $cmd in
  ui|--ui)
    lxrandr
    exit
    ;;
  mirror)
    if [ $mons_num -eq 2 ]; then
      mons -m
    else
      log_i screen "Not possible to mirror screen"
      notify Screen "Not possible to mirror screen"
    fi
    ;;
  single|reset)
    mons_num=1
    reset_xrandr
    auto_monitor
    ;;
  auto|udev|*)
    reset_xrandr
    auto_monitor
    compositor
    ;;
esac

notify Screen "${mons_num} monitor(s) detected"
