#!/usr/bin/env bash
# Usage: i3dm screensaver [option]
# Summary: Screensaver manager
# Help: The following options are available
# -e/enable - ensure screensaver is running
# -t/toggle - enable/disable screensaver
# -l/lock - lock screen

source ${libs_file}

function enable_screensaver(){
  LL=$(pgrep light-locker)

  if [ $? -ne 0 ]; then
      /usr/bin/light-locker &
      notify Screensaver enabled
  fi

}

function toggle() {
  LL=$(pgrep light-locker)

  if [ $? -eq 0 ]; then
      kill $LL
      notify Screensaver disabled
  else
      /usr/bin/light-locker &
      notify Screensaver enabled
  fi
}

function lock() {
  light-locker-command -l
}


command="$1"

case "$command" in
  "enable" | "-e")
    enable_screensaver
    ;;
  "toggle" | "-t")
    toggle
    ;;
  "lock" | "-l")
    lock
    ;;
  * )
    log_e $APP_NAME "Missing parameter: <toogle|lock>"
    ;;
esac
