#!/usr/bin/env bash
# Usage: i3dm input
# Summary: Adjust input devices

set -x

source ${libs_file}


# fix keyboard layout
/usr/bin/setxkbmap -model thinkpad60 -layout br
# Synaptics Touchpad (vertical and horizontal natural scrolling)
xinput --set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Two-Finger Scrolling" 1 1
xinput --set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Scrolling Distance" -99 -99

xinput --set-prop "Synaptics TM2722-001" "Synaptics Two-Finger Scrolling" 1 1
xinput --set-prop "Synaptics TM2722-001" "Synaptics Scrolling Distance" -99 -99

