#!/usr/bin/env bash
# Usage: i3dm launch [option]
# Summary: App/file launcher & window switcher
# Help: The following options are available
# -p/pass - password store mode
# -w/window - switch window mode
# -a/app - launch app mode

set -x

source ${libs_file}

DMENU_PARAMS="-b -i -p ❯ -fn Hack-11 -nb #000000 -nf #707070 -sb #000000 -sf #FFFFFF"

function switchwindow() {
  ids=$(xprop -root |grep _NET_CLIENT_LIST_STACKING\(WINDOW\) |cut -d"#" -f2| tr -d " "|tr "," " ")

  for id in $ids; do
    names="$names $(xprop -id $id| grep WM_CLASS |tr -d '" '|cut -d "=" -f2|awk -F "," '{print $NF}')($id)"
  done

  # Show Open window class names as a dmenu option
  target=$(echo $names | tr " " "\n" | dmenu $DMENU_PARAMS | grep -Eo "\(.*\)" | tr -d "()" )

  # switch to chosen window
  i3-msg [id="$target"] focus
}

function launcher() {
  case "$command" in
    "apps")
      i3-dmenu-desktop --dmenu="dmenu ${DMENU_PARAMS}"
      ;;
    "pass")
      passmenu --type ${DMENU_PARAMS}
      ;;
    "windows")
      switchwindow
      ;;
    "suspend")
      systemctl suspend
      ;;
    "kill")
      processList=$(ps -u $(whoami) -o pid= -o comm=)
      selection=$(echo -e "$processList" | dmenu ${DMENU_PARAMS})
      [[ -z "$selection" ]] && exit

      pid=$(awk '{print $1}' <<< "$selection" | tr '\n' ' ')
      [[ -z "$pid" ]] && exit

      kill "$pid"
      ;;
    "terminal" | "console")
      for i in $(tmux ls | grep "bz-" | grep -v "attached" | cut -d":" -f1); do tmux kill-session -t $i; done
      tmux has-session -t bz
      if [ $? -eq 0 ]; then
        TMUX_CMD="tmux new -t bz"
      else
        tmux new-session -d  -s bz
        TMUX_CMD="tmux new -t bz"
      fi

      /usr/bin/alacritty --command $TMUX_CMD
      ;;
    "monitor")
      list=("auto\nsingle\nui\nmirror")
      command=$(echo -e "$list" | dmenu ${DMENU_PARAMS})
      $(dirname $0)/../i3dm screenctl $command
      ;;
    *)
      list=("apps\npass\nwindows\nterminal\nmonitor\nsuspend\nkill")
      command=$(echo -e "$list" | dmenu ${DMENU_PARAMS})
      launcher
      ;;
  esac
}

command=$1
launcher
